spring:
  datasource:
    url: jdbc:h2:mem:dormitory
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: false
app:
  security:
    access-token:
      b64-secret: YWNjZXNzLXNlY3JldC1kZXY=
    refresh-token:
      b64-secret: cmVmcmVzaC1zZWNyZXQtZGV2
