spring:
  application:
    name: identity
  datasource:
    url: jdbc:mysql://identity-db/dormitory
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        jdbc:
          time_zone: UTC
server:
  error:
    include-stacktrace: never
app:
  security:
    issuer: ${ISSUER_NAME:auth}
    access-token:
      lifetime: ${ACCESS_TOKEN_LIFETIME:120} #2 minutes
      b64-secret: ${ACCESS_TOKEN_SECRET}
    refresh-token:
      lifetime: ${REFRESH_TOKEN_LIFETIME:604800} #7 days
      b64-secret: ${REFRESH_TOKEN_SECRET}
    audiences:
      - name: gql

